### PR TITLE
Update to haml-lint 0.34.2

### PR DESCRIPTION
**Pull request by michaelherold**

### CODE REVIEW

**Comment by jewilmeer** [comment]
would be awesome to see this merged. Bonus points to get it running in code climate with this or the latest version.

Can I be of any help?

**Comment by michaelherold** [comment]
Ah, yeah, I remember doing this now. It was back when Travis cut down on their open source infrastructure. That's why I never merged it.

I'm not using Haml in any projects anymore so this isn't naturally in my list of priorities right now.

We'll need to change the CI system to GitHub Actions because Travis is defunct. It's also a pain to get CodeClimate to update it in their infrastructure; you have to contact them in their Slack.

I'll get to this when I can, but I'm prepping for the birth of my second child who will be here soon so my open source time is limited.

Would you be interested in becoming a maintainer? Since I'm not using it anymore, I won't be the most attentive steward.

**Comment by jewilmeer** [comment]
Hi @michaelherold 

Congrats on the expected baby. I really enjoyed the time around the birth of our second child. It was less stressful then our first :-)

I would like to get a go on changing the CI first. If that works I would consider becoming a maintainer.

Our of curiosity, to what template engine did you switch?

**Comment by michaelherold** [comment]
> Our of curiosity, to what template engine did you switch?

I didn't so much switch engines as switched companies. 😄 At Shopify, we use either React or ERB for all rendering, no Haml in sight.

> I would like to get a go on changing the CI first. If that works I would consider becoming a maintainer.

Great to hear. I saw your PR in #20. I'll review it then write up docs for maintaining the engine next time I'm on my laptop with some free time. Should be in the next couple of days.

Thanks for contributing!

**Comment by michaelherold** [comment]
Closing because there have been many versions released since I wrote this.

**Comment by michaelherold** [comment]
I ran out of time today but will get to updating to a new version (v0.37.1) soon unless you'd like to, @jewilmeer.

**Comment by jewilmeer** [comment]
@michaelherold We've decided to also move away from HAML, and convert the templates to erb instead. That means I won't be using the linter as well. 

Thanks for the help!

**Pull request closed without merging**
